[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm --prefix apps/web install --include=dev",
  "npm --prefix apps/api install --include=dev"
]

[phases.build]
cmds = [
  "npm --prefix apps/web run build",
  "npm --prefix apps/api run build"
]

[start]
cmd = "node start.js"
